# Site settings
title: NerdLab YYC
email: nerdlabyyc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  NerdLab YYC is a community for feminist nerds who work in tech, including friends and allies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nerdlabyyc.com" # the base hostname & protocol for your site
enforce_ssl: nerdlabyyc.com
twitter_username: nerdlabyyc
github_username:  nerdlabyyc
permalink: pretty

# Build settings
markdown: kramdown
